name: Containerize app

on:
  workflow_run:
    workflows: ["Test"]

jobs:
  containerize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build . -t rest

        