name: Test

on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17.x, 1.19.x]

    steps:
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/checkout@v3

      - name: Test
        run: go test ./...